const AppError = require("./AppError");

const TRANSITIONS = {
  DOCUMENTARY_SUBMISSION: {
    DRAFT: ["SUBMITTED", "ARCHIVED"],
    SUBMITTED: ["UNDER_REVIEW", "ARCHIVED"],
    UNDER_REVIEW: ["NEEDS_INFORMATION", "VERIFIED", "REJECTED"],
    NEEDS_INFORMATION: ["SUBMITTED", "UNDER_REVIEW", "ARCHIVED"],
    VERIFIED: ["PUBLISHED", "ARCHIVED"],
    REJECTED: ["ARCHIVED"],
    PUBLISHED: ["ARCHIVED"],
    ARCHIVED: [],
  },
  SUPPORT_CASE: {
    NEW: ["UNDER_REVIEW", "REJECTED", "CLOSED"],
    UNDER_REVIEW: ["ACTION_REQUIRED", "VERIFICATION_PENDING", "REJECTED", "CLOSED"],
    ACTION_REQUIRED: ["UNDER_REVIEW", "VERIFICATION_PENDING", "CLOSED"],
    VERIFICATION_PENDING: ["VERIFIED", "ACTION_REQUIRED", "REJECTED"],
    VERIFIED: ["SUPPORT_IN_PROGRESS", "RESOLVED", "CLOSED"],
    SUPPORT_IN_PROGRESS: ["RESOLVED", "ACTION_REQUIRED", "CLOSED"],
    RESOLVED: ["CLOSED", "SUPPORT_IN_PROGRESS"],
    REJECTED: ["CLOSED"],
    CLOSED: [],
  },
  MISSING_PERSON_REPORT: {
    DRAFT: ["PENDING_REVIEW", "CLOSED"],
    PENDING_REVIEW: ["NEEDS_INFORMATION", "VERIFIED_MISSING", "FALSE_REPORT", "CLOSED"],
    NEEDS_INFORMATION: ["PENDING_REVIEW", "CLOSED"],
    VERIFIED_MISSING: ["FOUND_ALIVE", "FOUND_DECEASED", "FALSE_REPORT", "CLOSED"],
    FOUND_ALIVE: ["CLOSED"],
    FOUND_DECEASED: ["CLOSED"],
    FALSE_REPORT: ["CLOSED"],
    CLOSED: [],
  },
  CONVERSATION: {
    OPEN: ["WAITING_FOR_USER", "WAITING_FOR_ADMIN", "RESOLVED", "CLOSED"],
    WAITING_FOR_USER: ["OPEN", "WAITING_FOR_ADMIN", "RESOLVED", "CLOSED"],
    WAITING_FOR_ADMIN: ["OPEN", "WAITING_FOR_USER", "RESOLVED", "CLOSED"],
    RESOLVED: ["OPEN", "CLOSED"],
    CLOSED: ["OPEN"],
  },
  JULY_EVENT: {
    DRAFT: ["VERIFIED", "ARCHIVED"],
    VERIFIED: ["PUBLISHED", "DRAFT", "ARCHIVED"],
    PUBLISHED: ["VERIFIED", "ARCHIVED"],
    ARCHIVED: ["DRAFT"],
  },
  DOCUMENTARY_ITEM: {
    DRAFT: ["PUBLISHED", "ARCHIVED"],
    PUBLISHED: ["HIDDEN", "ARCHIVED"],
    HIDDEN: ["PUBLISHED", "ARCHIVED"],
    ARCHIVED: ["DRAFT"],
  },
  REVIEW: {
    PENDING: ["IN_PROGRESS", "NEEDS_INFORMATION", "VERIFIED", "REJECTED"],
    IN_PROGRESS: ["NEEDS_INFORMATION", "VERIFIED", "REJECTED"],
    NEEDS_INFORMATION: ["IN_PROGRESS", "VERIFIED", "REJECTED"],
    VERIFIED: ["IN_PROGRESS"],
    REJECTED: ["IN_PROGRESS"],
  },
  SIGHTING: {
    SUBMITTED: ["UNDER_REVIEW", "REJECTED", "DUPLICATE"],
    UNDER_REVIEW: ["VERIFIED", "REJECTED", "DUPLICATE"],
    VERIFIED: ["UNDER_REVIEW"],
    REJECTED: ["UNDER_REVIEW"],
    DUPLICATE: ["UNDER_REVIEW"],
  },
  DOCUMENT_REQUEST: {
    REQUESTED: ["SUBMITTED", "REJECTED"],
    SUBMITTED: ["UNDER_REVIEW", "REJECTED"],
    UNDER_REVIEW: ["APPROVED", "REJECTED", "SUBMITTED"],
    APPROVED: [],
    REJECTED: ["SUBMITTED"],
  },
};

function assertTransition(type, currentStatus, nextStatus) {
  if (currentStatus === nextStatus) return;
  const allowed = TRANSITIONS[type]?.[currentStatus] || [];
  if (!allowed.includes(nextStatus)) {
    throw new AppError(
      `Status cannot change from ${currentStatus} to ${nextStatus}. Allowed next statuses: ${allowed.join(", ") || "none"}.`,
      422,
      "INVALID_STATUS_TRANSITION",
      { type, currentStatus, nextStatus, allowed }
    );
  }
}

module.exports = { assertTransition, TRANSITIONS };
