const USER_ROLES = ["USER", "ADMIN"];
const ACCOUNT_STATUSES = ["ACTIVE", "SUSPENDED", "BLOCKED"];
const LANGUAGES = ["BN", "EN"];

const STORAGE_PROVIDERS = ["CLOUDINARY"];
const FILE_TYPES = ["IMAGE", "VIDEO", "AUDIO", "PDF", "DOCUMENT"];
const MEDIA_VISIBILITIES = ["PUBLIC", "PRIVATE", "ADMIN_ONLY"];
const UPLOAD_STATUSES = ["UPLOADING", "PROCESSING", "READY", "FAILED"];
const MODERATION_STATUSES = ["PENDING", "APPROVED", "REJECTED"];

const LOCATION_TYPES = [
  "COUNTRY",
  "DIVISION",
  "DISTRICT",
  "UPAZILA",
  "CITY",
  "AREA",
  "LANDMARK",
];

const EVENT_TYPES = [
  "PROTEST",
  "CLASH",
  "MARCH",
  "ARREST",
  "INJURY",
  "DEATH",
  "INTERNET_SHUTDOWN",
  "OTHER",
];
const EVENT_STATUSES = ["DRAFT", "VERIFIED", "PUBLISHED", "ARCHIVED"];

const SUBMISSION_TYPES = [
  "STORY",
  "IMAGE",
  "VIDEO",
  "AUDIO",
  "DOCUMENT",
  "TESTIMONY",
  "CORRECTION",
];
const SOURCE_TYPES = [
  "FIRST_HAND",
  "WITNESS",
  "FAMILY_MEMBER",
  "NEWS_SOURCE",
  "SOCIAL_MEDIA",
  "UNKNOWN",
];
const ANONYMITY_PREFERENCES = [
  "SHOW_NAME",
  "HIDE_NAME",
  "SHOW_PSEUDONYM",
];
const SUBMISSION_STATUSES = [
  "DRAFT",
  "SUBMITTED",
  "UNDER_REVIEW",
  "NEEDS_INFORMATION",
  "VERIFIED",
  "REJECTED",
  "PUBLISHED",
  "ARCHIVED",
];
const DOCUMENTARY_CONTENT_TYPES = [
  "STORY",
  "IMAGE_GALLERY",
  "VIDEO",
  "AUDIO",
  "DOCUMENT",
  "TESTIMONY",
];
const DOCUMENTARY_ITEM_STATUSES = [
  "DRAFT",
  "PUBLISHED",
  "HIDDEN",
  "ARCHIVED",
];

const REVIEW_TARGET_TYPES = [
  "DOCUMENTARY_SUBMISSION",
  "SUPPORT_CASE",
  "MISSING_PERSON_REPORT",
  "MISSING_PERSON_SIGHTING",
  "MEDIA_ASSET",
];
const REVIEW_STATUSES = [
  "PENDING",
  "IN_PROGRESS",
  "NEEDS_INFORMATION",
  "VERIFIED",
  "REJECTED",
];
const VERIFICATION_CHECK_TYPES = [
  "IDENTITY",
  "DATE",
  "LOCATION",
  "SOURCE",
  "MEDIA_AUTHENTICITY",
  "DUPLICATE",
  "MEDICAL_DOCUMENT",
  "FAMILY_CONFIRMATION",
];
const CHECK_STATUSES = ["PENDING", "PASSED", "FAILED"];

const CONVERSATION_TYPES = [
  "SUPPORT_ROOM",
  "DOCUMENTARY_REVIEW",
  "MISSING_PERSON_REVIEW",
  "GENERAL_ENQUIRY",
];
const CONVERSATION_SUBJECT_TYPES = [
  "SUPPORT_CASE",
  "DOCUMENTARY_SUBMISSION",
  "MISSING_PERSON_REPORT",
  "NONE",
];
const CONVERSATION_STATUSES = [
  "OPEN",
  "WAITING_FOR_USER",
  "WAITING_FOR_ADMIN",
  "RESOLVED",
  "CLOSED",
];
const PARTICIPANT_ROLES = ["OWNER", "TRUSTED_PARTICIPANT", "ADMIN"];
const INVITATION_STATUSES = ["PENDING", "ACCEPTED", "REJECTED", "REMOVED"];
const MESSAGE_TYPES = [
  "TEXT",
  "FILE",
  "IMAGE",
  "VIDEO",
  "SYSTEM_UPDATE",
  "DOCUMENT_REQUEST",
  "STATUS_UPDATE",
];
const MESSAGE_VISIBILITIES = ["ALL_PARTICIPANTS", "ADMIN_ONLY"];
const DOCUMENT_REQUEST_TARGET_TYPES = [
  "SUPPORT_CASE",
  "DOCUMENTARY_SUBMISSION",
  "MISSING_PERSON_REPORT",
];
const DOCUMENT_TYPES = [
  "NID",
  "BIRTH_CERTIFICATE",
  "MEDICAL_REPORT",
  "PRESCRIPTION",
  "HOSPITAL_DOCUMENT",
  "PHOTOGRAPH",
  "VIDEO_SOURCE",
  "RELATIONSHIP_PROOF",
  "OTHER",
];
const DOCUMENT_REQUEST_STATUSES = [
  "REQUESTED",
  "SUBMITTED",
  "UNDER_REVIEW",
  "APPROVED",
  "REJECTED",
];

const SUPPORT_RELATIONSHIPS = [
  "SELF",
  "PARENT",
  "SIBLING",
  "SPOUSE",
  "RELATIVE",
  "FRIEND",
  "REPRESENTATIVE",
];
const SUPPORT_PRIORITIES = ["LOW", "NORMAL", "HIGH", "URGENT", "CRITICAL"];
const SUPPORT_CASE_STATUSES = [
  "NEW",
  "UNDER_REVIEW",
  "ACTION_REQUIRED",
  "VERIFICATION_PENDING",
  "VERIFIED",
  "SUPPORT_IN_PROGRESS",
  "RESOLVED",
  "REJECTED",
  "CLOSED",
];
const ASSISTANCE_TYPES = [
  "MEDICAL_APPOINTMENT",
  "MEDICINE",
  "SURGERY",
  "REHABILITATION",
  "FINANCIAL",
  "LEGAL",
  "TRANSPORT",
  "OTHER",
];
const ASSISTANCE_STATUSES = [
  "PLANNED",
  "APPROVED",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
];

const MISSING_PERSON_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "NEEDS_INFORMATION",
  "VERIFIED_MISSING",
  "FOUND_ALIVE",
  "FOUND_DECEASED",
  "FALSE_REPORT",
  "CLOSED",
];
const SIGHTING_CONFIDENCE_LEVELS = ["LOW", "MEDIUM", "HIGH"];
const SIGHTING_STATUSES = [
  "SUBMITTED",
  "UNDER_REVIEW",
  "VERIFIED",
  "REJECTED",
  "DUPLICATE",
];

const NOTIFICATION_TYPES = [
  "NEW_MESSAGE",
  "STATUS_CHANGED",
  "DOCUMENT_REQUESTED",
  "SUBMISSION_APPROVED",
  "SUBMISSION_REJECTED",
  "MISSING_PERSON_UPDATE",
  "SUPPORT_UPDATE",
];
const NOTIFICATION_ENTITY_TYPES = [
  "SUPPORT_CASE",
  "DOCUMENTARY_SUBMISSION",
  "MISSING_PERSON_REPORT",
  "CONVERSATION",
];
const ADMIN_NOTE_TARGET_TYPES = [
  "SUPPORT_CASE",
  "DOCUMENTARY_SUBMISSION",
  "DOCUMENTARY_ITEM",
  "MISSING_PERSON_REPORT",
  "MISSING_PERSON_SIGHTING",
];
const CONSENT_TARGET_TYPES = [
  "DOCUMENTARY_SUBMISSION",
  "SUPPORT_CASE",
  "MISSING_PERSON_REPORT",
];
const CONSENT_TYPES = [
  "DATA_PROCESSING",
  "PUBLICATION",
  "MEDICAL_DATA_PROCESSING",
  "IDENTITY_VERIFICATION",
  "CONTACT_SHARING",
  "FAMILY_PARTICIPANT_ACCESS",
];
const MODERATION_TARGET_TYPES = [
  "DOCUMENTARY_ITEM",
  "MESSAGE",
  "USER",
  "MISSING_PERSON_REPORT",
];
const MODERATION_REASONS = [
  "FALSE_INFORMATION",
  "ABUSE",
  "HARASSMENT",
  "PRIVACY_VIOLATION",
  "DUPLICATE",
  "GRAPHIC_CONTENT",
  "OTHER",
];
const MODERATION_REPORT_STATUSES = [
  "OPEN",
  "UNDER_REVIEW",
  "RESOLVED",
  "REJECTED",
];
const AUDIT_ACTIONS = [
  "CREATE",
  "UPDATE",
  "DELETE",
  "VERIFY",
  "REJECT",
  "PUBLISH",
  "UNPUBLISH",
  "VIEW_SENSITIVE_DATA",
  "DOWNLOAD_PRIVATE_FILE",
  "ADD_PARTICIPANT",
  "REMOVE_PARTICIPANT",
  "CHANGE_STATUS",
];

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUSES,
  LANGUAGES,
  STORAGE_PROVIDERS,
  FILE_TYPES,
  MEDIA_VISIBILITIES,
  UPLOAD_STATUSES,
  MODERATION_STATUSES,
  LOCATION_TYPES,
  EVENT_TYPES,
  EVENT_STATUSES,
  SUBMISSION_TYPES,
  SOURCE_TYPES,
  ANONYMITY_PREFERENCES,
  SUBMISSION_STATUSES,
  DOCUMENTARY_CONTENT_TYPES,
  DOCUMENTARY_ITEM_STATUSES,
  REVIEW_TARGET_TYPES,
  REVIEW_STATUSES,
  VERIFICATION_CHECK_TYPES,
  CHECK_STATUSES,
  CONVERSATION_TYPES,
  CONVERSATION_SUBJECT_TYPES,
  CONVERSATION_STATUSES,
  PARTICIPANT_ROLES,
  INVITATION_STATUSES,
  MESSAGE_TYPES,
  MESSAGE_VISIBILITIES,
  DOCUMENT_REQUEST_TARGET_TYPES,
  DOCUMENT_TYPES,
  DOCUMENT_REQUEST_STATUSES,
  SUPPORT_RELATIONSHIPS,
  SUPPORT_PRIORITIES,
  SUPPORT_CASE_STATUSES,
  ASSISTANCE_TYPES,
  ASSISTANCE_STATUSES,
  MISSING_PERSON_STATUSES,
  SIGHTING_CONFIDENCE_LEVELS,
  SIGHTING_STATUSES,
  NOTIFICATION_TYPES,
  NOTIFICATION_ENTITY_TYPES,
  ADMIN_NOTE_TARGET_TYPES,
  CONSENT_TARGET_TYPES,
  CONSENT_TYPES,
  MODERATION_TARGET_TYPES,
  MODERATION_REASONS,
  MODERATION_REPORT_STATUSES,
  AUDIT_ACTIONS,
};
