import { ArrowRight, FileText, HeartHandshake, LockKeyhole, MessageSquareText, ShieldAlert } from "lucide-react";
import PageHeader from "../../components/ui/PageHeader";
import Button from "../../components/ui/Button";
import { supportBenefits } from "../../data/landingData";

const process = ["Request submitted", "Admin review", "Information checked", "Support coordination", "Progress updated", "Case completed"];

export default function SupportPage() {
  return (
    <>
      <PageHeader label="Private support workflow" title="Support Rooms for injured people and affected families" description="Submit a support need, communicate with authorised administrators and follow every update in one protected room." actions={<><Button to="/support/new" showArrow>Open Support Request</Button><Button to="/account/support-rooms" variant="secondary">My Support Rooms</Button></>} />
      <section className="section-pad"><div className="page-shell grid gap-10 lg:grid-cols-[.9fr_1.1fr]">
        <div><p className="eyebrow">How it works</p><h2 className="mt-3 font-display text-5xl font-semibold">A clear process after the form.</h2><p className="muted-copy mt-5">The room gives the requester a protected place for messages, requested documents, status updates and next steps.</p><div className="mt-8 space-y-4">{supportBenefits.map(({ title, description, icon: Icon }) => <div key={title} className="flex gap-4 rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5"><Icon className="h-6 w-6 shrink-0 text-archive-teal" /><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-archive-muted">{description}</p></div></div>)}</div></div>
        <div className="rounded-2xl border border-archive-teal/20 bg-[#0D1718]/60 p-6 sm:p-8"><div className="flex items-center gap-3"><HeartHandshake className="h-7 w-7 text-archive-teal" /><h2 className="font-display text-3xl font-semibold">Support process</h2></div><div className="mt-8 space-y-0">{process.map((step, index) => <div key={step} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 grid h-9 w-9 shrink-0 place-items-center rounded-full border border-archive-teal/30 bg-ink-950 text-sm font-bold text-archive-teal">{index + 1}</div>{index < process.length - 1 && <div className="absolute left-[17px] top-9 h-full w-px bg-white/10" />}<div><h3 className="font-semibold text-white">{step}</h3><p className="mt-1 text-sm text-archive-muted">{index === 0 ? "Provide only the information needed to understand the request." : index === 1 ? "An authorised administrator checks completeness and urgency." : index === 2 ? "The team may request a specific document or clarification." : index === 3 ? "Appropriate external support coordination can begin." : index === 4 ? "Every meaningful change appears in the private room." : "The request is closed with a recorded outcome."}</p></div></div>)}</div></div>
      </div></section>
      <section className="section-pad border-y border-archive-rose/10 bg-[#160E13]/60"><div className="page-shell grid gap-6 md:grid-cols-[auto_1fr_auto] md:items-center"><span className="grid h-14 w-14 place-items-center rounded-2xl border border-archive-rose/25 bg-archive-rose/10 text-archive-rose"><ShieldAlert className="h-7 w-7" /></span><div><h2 className="font-display text-3xl font-semibold">This platform is not an emergency hotline.</h2><p className="mt-2 text-sm leading-6 text-[#CDB8BC]">For immediate danger or urgent medical emergencies, contact local emergency services or go to the nearest appropriate medical facility.</p></div><Button to="/support/new" variant="rose">Create non-emergency request <ArrowRight className="h-4 w-4" /></Button></div></section>
      <section className="section-pad"><div className="page-shell grid gap-5 md:grid-cols-3">{[{title:"Messages",icon:MessageSquareText,text:"Keep case communication organised and visible to authorised participants."},{title:"Requested documents",icon:FileText,text:"Upload only the document requested for the case; avoid unrelated sensitive files."},{title:"Protected access",icon:LockKeyhole,text:"Public archive visitors cannot access support-room content."}].map(({title,icon:Icon,text}) => <article key={title} className="surface-card rounded-2xl p-6"><Icon className="h-6 w-6 text-archive-amber"/><h2 className="mt-5 font-display text-2xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-archive-muted">{text}</p></article>)}</div></section>
    </>
  );
}
